version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
      auth:
        ussername: mydockerhub-user
        password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: yarn install
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
